import = [
  "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

#import = [
#  "~/.config/alacritty/themes/themes/solarized_osaka.toml"
#]


[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.925 

option_as_alt = "Both"

[font]
normal.family = "MesloLGS NF"
size = 22 
